%YAML:1.0
debugMode: 0
printSchedule: 0
TIME_LIMIT: 600 # seconds, -1 means unlimited time
SKIP_PERM: 1


#*************************************************************
# Task set settings
priorityMode: RM
# test_n30_v1 requies many permutations
# test_n5_v41 test_n30_v3
testDataSetName: test_n5_v4
TIME_SCALE_FACTOR: 10
CHAIN_NUMBER: 1


#*************************************************************
# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000

