%YAML:1.0
debugMode: 0
printSchedule: 1
TIME_LIMIT: 600 # seconds, -1 means unlimited time
SKIP_PERM: 2
SearchDP: 1
SearchDP_Friendly: 1
# the proportion of permutations to keep! 1 means no sampling
SAMPLE_SMALL_TASKS: 1


#*************************************************************
# Task set settings
priorityMode: RM
# test_n5_v9 test_n5_v16 requies many permutations
# test_n5_v41 test_n30_v2  test_n5_v22 
# test_n5_v27 is a long case
testDataSetName: test_n5_v27
TIME_SCALE_FACTOR: 10
CHAIN_NUMBER: 2


#*************************************************************

# Cplex settings
kCplexInequalityThreshold: 1e0

# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000


