%YAML:1.0
debugMode: 0
printSchedule: 0
TIME_LIMIT: 600 # seconds, -1 means unlimited time



#*************************************************************
# Task set settings
priorityMode: orig
testDataSetName: test_n30_v1
timeScaleFactor: 10

#*************************************************************
# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000

