%YAML:1.0
debugMode: 0
TIME_LIMIT: 10 # seconds, -1 means unlimited time
SKIP_PERM: 1
# the proportion of permutations to keep! 1 means no sampling
SAMPLE_SMALL_TASKS: 0
SAMPLE_FEASIBLE_CHAINS: 0
FEASIBLE_CHAINS_MAX: 10
# 100, test_n10_v9, 600s, stop at 479-5
# 50, test_n10_v9, 560s, stop at 479-5
FEASIBLE_INCOMPLETE_CHAINS_MAX: 50
OPTIMIZE_JITTER_WEIGHT: 100

#*************************************************************
# Task set settings
priorityMode: RM
# test_n5_v9 test_n5_v16 
# test_n5_v41 test_n30_v2  test_n5_v22  test_n3_v24
# test_n5_v27 is a long case
testDataSetName: test_n5_v75
TIME_SCALE_FACTOR: 10
CHAIN_NUMBER: 999


#*************************************************************

# Cplex settings
kCplexInequalityThreshold: 1e0

# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000


